server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    absolute_redirect off;

    location / {
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Origin, Content-Type, Accept" always;

        if ($request_method = OPTIONS) {
            return 204;
        }

        try_files $uri $uri/ =404;
    }
}
